### ISSUE TITLE
Unexpected behaviour of navbar links

### ISSUE THREAD

**Issue by subhamkumarr** [MetaMask/metamask-docs#1139]
## Description:
When clicking on the `SDK` link, the color change effect is also automatically shown in the `Wallet` link. 

## Screenshot:

https://github.com/MetaMask/metamask-docs/assets/99977240/11a68faa-a9d7-4bfe-8afa-eda2a57c4dab

**Comment by subhamkumarr** [comment]
@alexandratran, may I work on this issue, ma'am?

**Comment by alexandratran** [comment]
@subhamkumarr This is the default behavior of the Docusaurus navbar links because the "SDK" label goes to a section that is *part of* of the "Wallet" sidebar. I don't know if there's an easy way to change the link behavior while keeping the SDK content as part of the wallet sidebar, but feel free to play around with it.

**Comment by subhamkumarr** [comment]
> @subhamkumarr This is the default behavior of the Docusaurus navbar links because the "SDK" label goes to a section that is _part of_ of the "Wallet" sidebar. I don't know if there's an easy way to change the link behavior while keeping the SDK content as part of the wallet sidebar, but feel free to play around with it.

Thank you for the clarification! I'm excited to dive in and see if there's a way to tweak the link behavior while maintaining the SDK content within the wallet sidebar. I'll explore the options and let you know if I come up with anything.
