### ISSUE TITLE
Add Starknet API docs

### ISSUE THREAD

**Issue by joaniefromtheblock** [MetaMask/metamask-docs#1516]
To add Starknet methods mentioned in this notion doc:

https://www.notion.so/consensys/Starknet-Snap-User-Guide-9d95a3863b4145c8a3bad6455e35e0e4

FYI, the methods that are rolled up in `get-starknet` include:

```
starkNet_extractPublicKey
starkNet_signTransaction
starkNet_signDeployAccountTransaction
starkNet_signDeclareTransaction
starkNet_executeTxn
starkNet_signMessage
starkNet_declareContract
starkNet_getStoredNetworks
starkNet_recoverAccounts
starkNet_switchNetwork
starkNet_addNetwork
starkNet_addErc20Token
starkNet_getCurrentNetwork
```

**Comment by alexandratran** [comment]
Questions:

- Is there anywhere that I can find more info about the following Starknet endpoints that are referenced in the spec return values?
  - `gateway/add_transaction`
  - `feeder_gateway/estimate_fee`
  - `feeder_gateway/call_contract`
  - `gateway/call_contract`

(Will add more questions as I go.)

**Comment by khanti42** [comment]
I think this document explains it https://starknetjs.com/docs/guides/walletAccount

In a nutshell : 

A dev will instantiate a wallet with get-starknet like this : 

```ts
import { connect } from 'get-starknet'; // v4.0.0 min
import { WalletAccount } from 'starknet'; // v6.10.0 min
const myFrontendProviderUrl = 'https://free-rpc.nethermind.io/sepolia-juno/v0_7';
// standard UI to select a wallet :
const selectedWalletSWO = await connect({ modalMode: 'alwaysAsk', modalTheme: 'light' });
const myWalletAccount = new WalletAccount({ nodeUrl: myFrontendProviderUrl }, selectedWalletSWO);
```

Once they get their `myWalletAccount` they can interact with the starknet network. 

- All reading activities will be done by the WalletAccount directly (not through the metamask wallet). That's why at the initialization of a WalletAccount, you need to put in the parameters a Provider instance. It will be used for all reading activities.
- To write to Starknet, the WalletAccount will ask the browser Wallet to sign and send the transaction, using the Starknet Wallet API to communicate.


So generally speaking any action that writes to the blockchain has to be implemented on our side. Then user can use the `myWalletAccount` as an object. 

For example if they need to sign a transaction they can simply do something like 

```
myWalletAccount.signTransaction 
```

Behind the scene this will trigger the snap to show up by calling the starkNet_signTransaction method. 


Other methods are related to the management of the wallet itself, like adding a new account, adding a new network, adding a new token, ...

**Comment by khanti42** [comment]
Regarding this specific questions : 

> What is the best way to describe the difference between the Starknet Snap JSON-RPC API, and the [Starknet JSON-RPC API](https://docs.metamask.io/services/reference/starknet/json-rpc-methods/)? 

Generally I agree, but specifically 

- Starknet Snap API: With the Starknet Snap installed, you can use the Starknet Snap API to interact with users' Starknet accounts (`i.e. write to the blockchain, e.g. submit transaction)` 
- Starknet API: You can use the Starknet API to ~interact~ `read` information from the Starknet network `(this does not require a wallet)`.

**Comment by alexandratran** [comment]
@khanti42 

Thanks for the info. Do you have any information on my first question?

> Is there anywhere that I can find more info about the following Starknet endpoints that are referenced in the spec return values?
> - gateway/add_transaction
> - feeder_gateway/estimate_fee
> - feeder_gateway/call_contract
> - gateway/call_contract

Also, regarding this:
> Starknet API: You can use the Starknet API to interact read information from the Starknet network (this does not require a wallet).

The first few methods of the Starknet API allow you to submit Starknet transactions (e.g. [`starknet_addDeclareTransaction`](https://docs.metamask.io/services/reference/starknet/json-rpc-methods/starknet_adddeclaretransaction/)) – this isn't just reading from the network?

**Comment by khanti42** [comment]
@alexandratran, the feeder_gateway/gateway has been [deprecated](https://community.starknet.io/t/feeder-gateway-deprecation/100233) and replaced by [RPC endpoints](https://docs.starknet.io/tools/api-services/). For some calls made by the StarkNet Snap, the response is simply the value returned by the RPC call to the StarkNet network (without any modifications). In those cases, the return value will follow the specifications of the corresponding RPC endpoint.

I will clarify this in a new review of PR #1509 by adding links to the appropriate sections of the StarkNet.js API documentation for those cases.
