### ISSUE TITLE
[bug] Click the transaction submit button repeatedly

### ISSUE THREAD

**Issue by hoyong6** [MetaMask/metamask-docs#192]
![image](https://user-images.githubusercontent.com/20646178/97544576-c9a29980-1a04-11eb-9081-b6515d491327.png)
I think the most throttling operation is needed

**Comment by BboyAkers** [comment]
@hoyong6 I recommend you create an issue in this repo https://github.com/MetaMask/metamask-mobile 🙂 . Sorry for the late response! Make sure to include your:
- phone OS build version
- phone type(make and model)
- version of MetaMask Mobile
- A step by step on recreating the issue.

I'm going to go ahead and close this issue since it's not related to MetaMask Docs. Please re-open this issue if the issue in the other repo goes silent, 🙂 I can try to look into it!
