### ISSUE TITLE
Guide for "Log in with MetaMask"

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/metamask-docs#318]
A common pattern is allowing the user to authenticate using MetaMask. Developers will often assume that the MetaMask "connect" flow is similar to a login, and that after connecting they can trust that the user is who our provider claims they are. But this is not safe, because any extension could inject their own provider that could let the user pretend to be anybody.

We should have a guide that explains how to implement a secure "Log in with MetaMask" functionality.

**Comment by BboyAkers** [comment]
If anyone isn't going to take this, I'd be happy to work on this or collaborate with one of the new devrel peeps on this 🙂 @Gudahtt

**Comment by Gudahtt** [comment]
@BboyAkers That would be great!

**Comment by obscurityceo** [comment]
So was this documented, or what is the status of this ticket?

**Comment by ndevmetax** [comment]
> A common pattern is allowing the user to authenticate using MetaMask. Developers will often assume that the MetaMask "connect" flow is similar to a login, and that after connecting they can trust that the user is who our provider claims they are. But this is not safe, because any extension could inject their own provider that could let the user pretend to be anybody.
> 
> We should have a guide that explains how to implement a secure "Log in with MetaMask" functionality.


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by httpJunkie** [comment]
@GuiBibeau and I can pick this up after October 26th 2022 if nobody else has done any significant work on it.

**Comment by Holybasil** [comment]
any updates?

**Comment by vandan** [comment]
We launched this page to encourage developers to implement [SIWE](https://docs.login.xyz/general-information/siwe-overview) recently: https://docs.metamask.io/wallet/how-to/use-siwe/

It doesn't explicitly describe the security related reasoning for using SIWE over the approach described in the original issue, but does reference the EIP-4361. @Gudahtt let me know if you think those resources cover this topic sufficiently. Otherwise, if you can describe the risks for developers who "rely on the MetaMask connect flow" as a login, then we can push that into the docs.

**Comment by Gudahtt** [comment]
That page seems like a good enough resource for now. We can consider adding another one later that covers non-SIWE strategies if there is a demand.
