### ISSUE TITLE
wallet_addEthereumChain http error

### ISSUE THREAD

**Issue by FFBrandynThibault** [MetaMask/metamask-docs#419]
I have a geth node running and I'm trying to create a button that adds the network info to users metamask. Being a geth node it uses http. I am using the wallet_addEthereumChain call but it completely rejects the rpc address saying it has to be https, the docs say that both are allowed but https is preferred.  Below is the call being made

`try {
            await window.ethereum.request({
              method: 'wallet_addEthereumChain',
              params: [
                {
                  chainId: '0x43',
                  chainName: 'CU dev network',
                  rpcUrls: ['http://the numbers leading to the node'],
                  nativeCurrency: 'eth',
                  blockExplorerUrls: null,
                },
              ],
            })
          } catch (error) {
            console.error('error adding eth network: ')
          }`

**Comment by unzsnu** [comment]
+1

**Comment by Cherasowy** [comment]
+1

**Comment by BboyAkers** [comment]
It says in the [spec](https://eips.ethereum.org/EIPS/eip-3085):
"All URL strings MUST include the protocol component of the URL. HTTPS SHOULD always be used over HTTP"

I also looked at the examples inside the spec and both of them use https. I apologize for the confusion!

3 things:
- The rejection could be via the browser due to browser security.
- Can you link where it says that in the docs so I can go ahead, update, and fix some verbiage around that 🙂 
- Can you past an example using codepen, codesandbox, ect.? I'd like to look more into!

Thanks a ton for filing this issue!! 🙂

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
Thanks

**Comment by BboyAkers** [comment]
Going to close due to inactivity! Please re-open if you have any more questions! 🙂
