### ISSUE TITLE
[Question] How do I detect I'm inside metamask mobile app

### ISSUE THREAD

**Issue by cainaleaouk** [MetaMask/metamask-docs#522]
Hi there,

As per documentation in the browser I check for MetaMask by doing
```
if (typeof window.ethereum !== 'undefined') {
  console.log('MetaMask is installed!');
}
```

To my surprise `window.ethereum` is undefined when loading my app inside the MetaMask mobile app. 
How does one detects it is inside of the app?

Cheers,
Cai

**Comment by httpJunkie** [comment]
You can reliably detect both the mobile and extension using the snippet:

But here is the snippet:
```javascript
if (window.ethereum) {
  handleEthereum();
} else {
  window.addEventListener('ethereum#initialized', handleEthereum, {
    once: true,
  });

  // If the event is not dispatched by the end of the timeout,
  // the user probably doesn't have MetaMask installed.
  setTimeout(handleEthereum, 3000); // 3 seconds
}

function handleEthereum() {
  const { ethereum } = window;
  if (ethereum && ethereum.isMetaMask) {
    console.log('Ethereum successfully detected!');
    // Access the decentralized web!
  } else {
    console.log('Please install MetaMask!');
  }
}
```

Since you are posting this issue in the documentation repo, I will point you to the docs where this is covered:
https://docs.metamask.io/guide/mobile-best-practices.html#the-provider-window-ethereum

If the code above confuses you, If you feel the documentation in the link above is lacking, let us know. If you have more specific questions about MetaMask mobile you could always open a separate issue in the [MetaMask Mobile repo](https://github.com/MetaMask/metamask-mobile):

**Comment by alexandratran** [comment]
Closing due to no further response.
